kotha/urls.py
from django.urls import path
from django.conf.urls import url
from django.views.generic.base import RedirectView
from .views import KothaCreateView, KothaListView, KothaDetailView, KothaUpdateView, KothaDeleteView

app_name = "kotha"

urlpatterns = [
    url(r'^$', RedirectView.as_view(url="/")),
    url(r'^search/$', KothaListView.as_view(), name="kotha-list"),
    url(r'^create/$', KothaCreateView.as_view(), name="kotha-create"),
    url(r'^(?P<pk>\d+)/$', KothaDetailView.as_view(), name="kotha-detail"),
    url(r'^(?P<pk>\d+)/update/$', KothaUpdateView.as_view(), name="kotha-update"),
    url(r'^(?P<pk>\d+)/delete/$', KothaDeleteView.as_view(), name="kotha-delete"),
]

kothon/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from  kotha.views import KothaListView
from accounts.views import UserRegisterView
from .views import home

app_name = "kothon"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', KothaListView.as_view(), name="home"),
    path('register/', UserRegisterView.as_view(), name="register"),
    path('kotha/', include("kotha.urls", namespace='kothon-kotha')),
    path('profiles/', include("accounts.urls", namespace='kothon-profiles')),
    path('api/kotha/', include("kotha.api.urls", namespace='kotha-api')),
]


if settings.DEBUG:
    urlpatterns += (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}"> 

    <title>{% block title %} {% endblock %}</title>

    <style>
        .grey-color{
          color: #ccc;
        }
        .red-color{
          color: red;
        }
    </style>
  </head>
  <body style="background: #E6ECF0;">
    
    {% include "navbar.html" %}

      <div class="container">
        {% block content %}
        {% endblock content %}
      </div>

      <div class="footer bg-dark py-5 mt-5">
          <div class="container">
              <div class="row">
                  <div class="col-sm-6 col-sm-offset-3 mx-auto">
                    <p class="text-center text-white">All rights reserved @Abid</p>
                  </div>
              </div>
          </div>
      </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    {% block scripts %}{% endblock scripts %}

    <!-- scripts for auto search  -->
    <script>
      $(document).ready(function(){
        var typingTimer;
        var doneInterval = 500;
        var searchInput = $("#nav-search-form input[type=text]")
        var searchQuery;

        searchInput.keyup(function(event){
            searchQuery = $(this).val()

            clearTimeout(typingTimer)
            typingTimer = setTimeout(doneSearchTyping, doneInterval)
        });

        searchInput.keydown(function(event){
            clearTimeout(typingTimer)
        });

        function doneSearchTyping(){
          if(searchQuery){
            var url = '/kotha/search/?q=' + searchQuery;
            document.location.href = url
          }
        }
      })
    </script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"  crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}
    Kothon.co
{% endblock title %}


{% block content %}
    Welcome to Kothon<3
{% endblock content %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-2">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">কথন</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto ml-5">

                <li class="nav-item">
                    <a class="nav-link" href="{% url "kothon-kotha:kotha-list" %}">কথন লিস্ট</a>
                </li>
            </ul>
            <ul class="navbar-nav ">
                <li class="nav-item">
                    {% include "kotha/search_form.html" %}
                </li>
                <li class="nav-item ml-4">
                    <form class="form-inline mt-1">
                        <button class="btn btn-sm mr-2 btn-outline-success" type="button">User</button>
                        <button class="btn btn-sm btn-outline-secondary" type="button"><a class="mybtn" href="{% url 'kothon-kotha:kotha-create' %}">Create Kotha</a></button>
                    </form>
                </li>
            </ul>
        </div>
    </div>
</nav>